# Generated by Django 5.0 on 2024-02-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_order_id_order__id_order_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
