# Generated by Django 5.0 on 2024-02-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order__id_alter_orderitem__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliverdAt',
            new_name='deliveredAt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brank',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='order',
            name='_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
